name: Wik
title: Wik - Warehouse Visualizing
description: Wahrehouse visiualizing library
author: ronnie
public_dir: dist
theme: hr
version: 1.0.5
menu:
  - text: Intro
    path: /
  - text: Quick
    path: /quick.html
  - text: Guides
    path: /guides
  - text: Posts
    path: /posts.html
  - text: API
    path: /api.html
