name: Wik
title: Wik - Warehouse Visualizing
description: Wahrehouse visiualizing library
author: ronnie
public_dir: dist
theme: hr
version: 1.0.5
menu:
  - text: 简介
    path: /
  - text: 入门
    path: /quick.html
  - text: 教程
    path: /guides
  - text: 博客
    path: /posts.html
  - text: API
    path: /api.html
